### ISSUE TITLE
what's your torchvision version?

### ISSUE THREAD

**Issue by GrayXu** [sergeywong/cp-vton#19]
I found error 
```
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    main()
  File "train.py", line 182, in main
    train_tom(opt, train_loader, model, board)
  File "train.py", line 100, in train_tom
    criterionVGG = VGGLoss()
  File "/work/CP-VTON/cp-vton-master/networks.py", line 388, in __init__
    self.vgg = Vgg19()
  File "/work/CP-VTON/cp-vton-master/networks.py", line 356, in __init__
    vgg_pretrained_features = models.vgg19(pretrained=True).features
TypeError: vgg19() got an unexpected keyword argument 'pretrained'
```

 on torchvision 0.1.6

**Comment by solitarysandman** [comment]
I can train using **torchvision==0.3.0**
Hope it helps!

**Comment by GrayXu** [comment]
0.2.0 also works
